name: Tests Execution

jobs:
  build_on_mac:
    runs-on: macos-latest
    outputs:
      macos_installer_filename: ${{ steps.upload_installer.outputs.asset_name }}
      macos_installer_hash: ${{ steps.upload_installer.outputs.asset_hash }}
      macos_exec_filename: ${{ steps.upload_exec.outputs.asset_name }}
      macos_exec_hash: ${{ steps.upload_exec.outputs.asset_hash }}
    steps:
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DEV_ID_APPLICATION_CERTIFICATE_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.APPLE_DEV_ID_DECRYPTION_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_DEV_ID_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: list identities
        run: echo $(security find-identity)
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Build Installer dist
        run: npm run make
        env:
          APPLE_IDENTITY: ${{secrets.APPLE_DEV_IDENTITY}}
          APPLE_ID: ${{secrets.APPLE_DEV_ID}}
          APPLE_DEV_ID_APP_SPECIFIC_PASSWORD: ${{secrets.APPLE_DEV_ID_APP_SPECIFIC_PASSWORD}}
          DEBUG: electron
      - name: Check sign app
        run: echo $(codesign -dvvv ./out/point-darwin-x64/point.app)

      - name: Build Installer
        run: npm run create-installer-mac
      - name: Compress and package executables
        run: ./scripts/package_macos_executables.sh
      - name: Check sign dmg
        run: echo $(codesign -dvvv ./out/point.dmg)
      - name: Compress and package Installer
        run: ./scripts/package_macos_installer.sh