version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  tests_linux:
    docker:
      - image: 'circleci/node:16-browsers'
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - node/install:
          node-version: '16.7.0'
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Download Point
          command: wget https://github.com/pointnetwork/pointnetwork-dashboard/releases/download/v0.2.74/point-v0.2.74-Linux-Debian-Ubuntu.tar.gz
      - run:
          name: Unzip Point
          command: gunzip -c point-v0.2.74-Linux-Debian-Ubuntu.tar.gz | tar xopf -
      - run:
          name: Install Dependencies Point
          command: sudo apt-get install libnotify4
      - run:
          name: Install Point
          command: sudo apt install ./point.deb
      - run:
          name: Decrypt credentials
          command : npm run decrypt-credentials
      - run:
          name: Test
          command: npm run simple-test-linux
      - store_artifacts:
          path: tests/reports/html-reports
      - store_artifacts:
          path: ~/.point/pointdashboard.log
      - store_artifacts:
          path: ~/.point/point.log


workflows:
  version: 2.1
  smoke_tests:
    jobs:
      - tests_linux




