name: Automated Tests
on:
  push:
    branches:
      - 'main'
jobs:
  mac-os-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Download App
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'pointnetwork/pointnetwork-dashboard/releases'
          file: 'point-v0.2.69-MacOS-app.zip'
      - name: Unzip File
        run: unzip point-v0.2.69-MacOS-app.zip
      - name: Run Tests
        run: |
          echo "Running Tests"
          npm run simple-test
        env:
          SECRET_WORDS: ALEXIS
      - name: Display Files
        if: always()
        run: ls
      - name: Upload HTML Report
        if: always()
        with:
          name: report
          path: "tests/reports/html-reports/"
