name: Automated Tests Linux
on:
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  linux-os-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'pointnetwork/pointnetwork-dashboard/releases'
          file: 'point-v0.2.69-Linux-Debian-Ubuntu.tar.gz'
      - name: Decrypt credentials
        env:
          PASS_ENCRYPT_AUTOMATION: ${{ secrets.DECRYPT_CREDENTIALS_PASS }}
        run: npm run decrypt-credentials
      - name: Unzip file
        run: gunzip -c point-v0.2.69-Linux-Debian-Ubuntu.tar.gz | tar xopf -
      - name: Install Point
        run: sudo dpkg -i point.deb
      - name: Run Tests
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run simple-test-linux
      - name: Upload HTML Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: report
          path: "tests/reports/html-reports/"
