name: Tests Execution
'on':
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  test_on_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: npm install
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'pointnetwork/pointnetwork-dashboard/releases'
          latest: true
          file: 'point-v0.2.61-MacOS-installer.tar.gz'
      - name: Unzip file
        run: gunzip -c point-v0.2.61-MacOS-installer.tar.gz | tar xopf -
      - name: Mount Point
        run: hdiutil attach point.dmg
      - name: Install Point
        run: cp -R /Volumes/point/point.app /Application
      - name: Run Tests
        run: |
          cd
          cd point-automation
          echo "Running tests"
          npm run simple-test
