name: Automated Tests Linux
on:
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  linux-os-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS }}
    steps:
      - name: Show context
        run: echo "$GITHUB_CONTEXT"
      - name: Show home
        run: echo "$HOME"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install FFMpeg
        run: sudo apt-get install ffmpeg
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'pointnetwork/pointnetwork-dashboard/releases'
          file: 'point-v0.2.76-Linux-Debian-Ubuntu.tar.gz'
      - name: Decrypt credentials
        env:
          PASS_ENCRYPT_AUTOMATION: ${{ secrets.DECRYPT_CREDENTIALS_PASS }}
        run: npm run decrypt-credentials
      - name: Unzip file
        run: gunzip -c point-v0.2.76-Linux-Debian-Ubuntu.tar.gz | tar xopf -
      - name: Install Point
        run: sudo dpkg -i point.deb && sudo apt-get install -f
      - name: Install XVFB
        run: sudo apt-get install xvfb
      - name: See procs
        run: sudo ps aux
      - name: See point procs
        run: sudo ps aux | grep point
      - name: Run Tests
        run: xvfb-run --auto-servernum npm run simple-test-linux
      - name: Run node
        if: always()
        run: ${HOME}/.point/bin/linux/point &
      - name: Run Tests
        if: always()
        run: xvfb-run --auto-servernum npm run simple-test-linux
      - name: See cur dir
        if: always()
        run: pwd
      - name: See files
        if: always()
        run: ls -fal
      - name: See files home
        if: always()
        run: ls -fal $HOME
      - name: See files home point
        if: always()
        run: ls -fal $HOME/.point
      - name: See files home point
        if: always()
        run: echo $HOME
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: report
          path: ${{ env.HOME }}/.point/*.log
      - name: See procs2
        if: always()
        run: sudo ps aux  | grep point