name: Tests Execution
'on':
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  test_on_mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: npm install
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'pointnetwork/pointnetwork-dashboard/releases'
          file: 'point-v0.2.64-MacOS-app.zip'
      - name: Display downloaded files
        run: ls
      - name: Display Path
        run: pwd
      - name: Unzip file
        run: unzip point-v0.2.64-MacOS-app.zip
      - name: Display unzipped files
        run: ls
      - name: Run Tests
        run: |
          echo "Running tests"
          npm run simple-test
