name: Automated Tests Linux
on:
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  linux-os-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PERSONAL_ACCESS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install FFMpeg
        run: sudo apt-get install ffmpeg
      - name: Download release
        run: wget https://github.com/aalvarezpoint/alexisbuilds/releases/download/alexis/point-v0.2.xx1-Linux-Debian-Ubuntu.tar.gz
      - name: Decrypt credentials
        env:
          PASS_ENCRYPT_AUTOMATION: ${{ secrets.DECRYPT_CREDENTIALS_PASS }}
        run: npm run decrypt-credentials
      - name: Unzip file
        run: gunzip -c point-v0.2.xx1-Linux-Debian-Ubuntu.tar.gz | tar xopf -
      - name: Install Point
        run: sudo dpkg -i point.deb && sudo apt-get install -f
      - name: Install XVFB
        run: sudo apt-get install xvfb
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
      - run: firefox --version
      - name: Run Tests
        run: xvfb-run --auto-servernum npm run test-linux
      - name: Upload HTML Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: report
          path: "tests/reports/html-reports/"
