name: Tests Execution
'on':
  workflow_dispatch:
    inputs:
      testsBranch:
        description: Automated Tests branch to use
        required: true
        default: main

jobs:
  test_on_mac:
    runs-on: macos-latest
    env:
      SECRET_WORDS: '${{ secrets.SECRET_WORDS }}'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.testsBranch || ''main'' }}'
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install
        run: npm install
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'aalvarezpoint/alexisbuilds/releases'
          file: 'point-v0.2.68-MacOS-app.zip'
      - name: Unzip file
        run: unzip point-v0.2.68-MacOS-app.zip
      - name: Run Tests
        run: |
          echo "Running tests"
          sudo npm run simple-test
      - name: Display Files
        if: always()
        run: ls
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: report
          path: "tests/reports/html-reports/"
